### ISSUE TITLE
boxzilla mailchimp update failed

### ISSUE THREAD

**Issue by jeremycrews** [ibericode/boxzilla-wp#112]
this has been a consistent issue since installing the add-on with the newest update (late October).

**Comment by arnelap** [comment]
I'm afraid the only solution is to manually download the latest version from your Boxzilla account page and install it that way. After that the issue should be solved. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/boxzilla or contact Premium support since you have a license for that. 

Thanks!
